version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: messenger
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgres/data
      - ./:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  server:
    image: "node"
    links:
      - "db:database"
    env_file:
      - ".env"
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/app
    working_dir: "/usr/app"
    command: npm start
